apiVersion: v1
kind: Secret
metadata:
  name: cake-delight-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://ajaypavushetti123_db_user:Ajay1234@cluster0.zjk35mk.mongodb.net/cake_delight?retryWrites=true&w=majority"
  RABBITMQ_URL: "amqps://ylomjnxq:8RbdOU4yjAGn-jLM_W2VZHytQc44lcSA@puffin.rmq2.cloudamqp.com/ylomjnxq"
