apiVersion: v1
kind: Secret
metadata:
  name: cake-delight-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb-service:27017/cake_delight"
  RABBITMQ_URL: "amqps://ylomjnxq:8RbdOU4yjAGn-jLM_W2VZHytQc44lcSA@puffin.rmq2.cloudamqp.com/ylomjnxq"
